/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.views;

/**
 *
 * @author Heshani
 */
public class DevicePanel extends javax.swing.JPanel {

    /**
     * Creates new form DevicePanel
     */
    public DevicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDev1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        deviceNameBtn = new javax.swing.JToggleButton();
        descLabel = new javax.swing.JLabel();

        panelDev1.setBackground(new java.awt.Color(255, 255, 255));
        panelDev1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelDev1.setMaximumSize(new java.awt.Dimension(330, 178));
        panelDev1.setMinimumSize(new java.awt.Dimension(330, 178));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\Industry-Rfid-Signal-icon.png")); // NOI18N

        deviceNameBtn.setBackground(new java.awt.Color(255, 255, 255));
        deviceNameBtn.setText("jToggleButton1");

        descLabel.setText("jLabel1");

        javax.swing.GroupLayout panelDev1Layout = new javax.swing.GroupLayout(panelDev1);
        panelDev1.setLayout(panelDev1Layout);
        panelDev1Layout.setHorizontalGroup(
            panelDev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDev1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
            .addComponent(deviceNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelDev1Layout.setVerticalGroup(
            panelDev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDev1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(deviceNameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDev1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(descLabel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDev1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel descLabel;
    public javax.swing.JToggleButton deviceNameBtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelDev1;
    // End of variables declaration//GEN-END:variables
}
