/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.views;

import javax.swing.JPanel;
import jpcap.NetworkInterface;

/**
 *
 * @author Heshani
 */
public class Home extends javax.swing.JFrame {
    
    public static JPanel containerPanel;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();

        setTitle("DeadLocks");
        buttonGroup.add(showDevicesButton);
        buttonGroup.add(analyzerButton);
        buttonGroup.add(predictorButton);

        setLocationRelativeTo(null);

        containerPanel = this.contentPanel;

        containerPanel.removeAll();
        containerPanel.add(new NetworkInterfacesPanel(), "networkInterfacesPanel", 0);
        containerPanel.revalidate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        menuPanel = new javax.swing.JPanel();
        analyzerButton = new javax.swing.JToggleButton();
        showDevicesButton = new javax.swing.JToggleButton();
        predictorButton = new javax.swing.JToggleButton();
        contentPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));

        analyzerButton.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\analyzer.png")); // NOI18N
        analyzerButton.setText("Analyzer");
        analyzerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        analyzerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        analyzerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        analyzerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzerButtonActionPerformed(evt);
            }
        });

        showDevicesButton.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\incoming.png")); // NOI18N
        showDevicesButton.setText("Network Interfaces");
        showDevicesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showDevicesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showDevicesButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        showDevicesButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        showDevicesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDevicesButtonActionPerformed(evt);
            }
        });

        predictorButton.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\predictor.png")); // NOI18N
        predictorButton.setText("Predictor");
        predictorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        predictorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        predictorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        predictorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(analyzerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(predictorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(showDevicesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(analyzerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(predictorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(showDevicesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(369, Short.MAX_VALUE)))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMinimumSize(new java.awt.Dimension(0, 0));

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDevicesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDevicesButtonActionPerformed

        containerPanel.removeAll();
        containerPanel.add(new NetworkInterfacesPanel(), "networkInterfacesPanel", 0);
        containerPanel.revalidate();

    }//GEN-LAST:event_showDevicesButtonActionPerformed

    private void analyzerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzerButtonActionPerformed

        containerPanel.removeAll();
        containerPanel.add(new TrafficAnalyserPanel(), "trafficAnalyserPanel", 0);
        containerPanel.revalidate();
    }//GEN-LAST:event_analyzerButtonActionPerformed

    private void predictorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictorButtonActionPerformed

        containerPanel.removeAll();
        containerPanel.add(new PredictorPanel(), "predictorPanel", 0);
        containerPanel.revalidate();
    }//GEN-LAST:event_predictorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton analyzerButton;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JToggleButton predictorButton;
    private javax.swing.JToggleButton showDevicesButton;
    // End of variables declaration//GEN-END:variables
}
