/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import org.jnetpcap.Pcap;
import org.jnetpcap.PcapIf;

/**
 *
 * @author Heshani
 */
public class NetworkInterfacesPanel extends javax.swing.JPanel {

    private List<PcapIf> networkInterfacesList;
    JToggleButton buttnList[];
    JLabel descList[];
    JLabel datalinkList[];
    JLabel datalinkDescList[];
    JPanel panelList[];

    /**
     * Creates new form networkInterfacesList
     */
    public NetworkInterfacesPanel() {
        initComponents();

        buttnList = new JToggleButton[6];
        descList = new JLabel[6];
        datalinkList = new JLabel[6];
        datalinkDescList = new JLabel[6];
        panelList = new JPanel[6];

        buttonGroup1.add(device1);
        buttonGroup1.add(device2);
        buttonGroup1.add(device3);
        buttonGroup1.add(device4);
        buttonGroup1.add(device5);
        buttonGroup1.add(device6);

        buttnList[0] = device1;
        buttnList[1] = device2;
        buttnList[2] = device3;
        buttnList[3] = device4;
        buttnList[4] = device5;
        buttnList[5] = device6;

        descList[0] = descDev1;
        descList[1] = descDev2;
        descList[2] = descDev3;
        descList[3] = descDev4;
        descList[4] = descDev5;
        descList[5] = descDev6;

        panelList[0] = panelDev1;
        panelList[1] = panelDev2;
        panelList[2] = panelDev3;
        panelList[3] = panelDev4;
        panelList[4] = panelDev5;
        panelList[5] = panelDev6;

        getNetworkInterfaces();
    }

    private void getNetworkInterfaces() {

        //get all NICs
        List<PcapIf> devices = new ArrayList<PcapIf>();
        //for any error msg
        StringBuilder errbuf = new StringBuilder();
        int r = Pcap.findAllDevs(devices, errbuf);
        if (r == Pcap.NOT_OK || devices.isEmpty()) {
            System.out.println("Can't read list of devices, error is " + errbuf.toString());
            return;
        }

        this.networkInterfacesList = devices;

        int index = 0;
        for (PcapIf device : devices) {

            buttnList[index].setText(device.getName());
            descList[index].setText(device.getDescription());

            //add action listener
            DeviceListener deviceListener = new DeviceListener();
            buttnList[index].addActionListener(deviceListener);

            index++;
        }

        for (int i = index; i < panelList.length; i++) {
            System.out.println(panelList[i]);
            this.remove(panelList[i]);
            this.revalidate();
            this.repaint();

        }
    }

    class DeviceListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            Home.containerPanel.removeAll();
            Home.containerPanel.add(new TrafficAnalyserPanel(networkInterfacesList, e.getActionCommand()), "trafficAnalyserPanel", 0);
            Home.containerPanel.revalidate();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        panelDev1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        device1 = new javax.swing.JToggleButton();
        descDev1 = new javax.swing.JLabel();
        panelDev4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        device4 = new javax.swing.JToggleButton();
        descDev4 = new javax.swing.JLabel();
        panelDev2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        device2 = new javax.swing.JToggleButton();
        descDev2 = new javax.swing.JLabel();
        panelDev3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        device3 = new javax.swing.JToggleButton();
        descDev3 = new javax.swing.JLabel();
        panelDev6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        device6 = new javax.swing.JToggleButton();
        descDev6 = new javax.swing.JLabel();
        panelDev5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        device5 = new javax.swing.JToggleButton();
        descDev5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1061, 480));
        setMinimumSize(new java.awt.Dimension(1061, 480));
        setPreferredSize(new java.awt.Dimension(905, 509));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("NETWORK INTERFACES");

        panelDev1.setBackground(new java.awt.Color(0, 153, 255));
        panelDev1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDev1.setMaximumSize(new java.awt.Dimension(330, 178));
        panelDev1.setMinimumSize(new java.awt.Dimension(330, 178));
        panelDev1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\Industry-Rfid-Signal-icon.png")); // NOI18N
        panelDev1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 76, -1, -1));

        device1.setBackground(new java.awt.Color(0, 153, 255));
        device1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        device1.setText("jToggleButton1");
        panelDev1.add(device1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 28, 320, 30));

        descDev1.setText("jLabel1");
        panelDev1.add(descDev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 76, 171, -1));

        panelDev4.setBackground(new java.awt.Color(255, 0, 204));
        panelDev4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDev4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\Industry-Rfid-Signal-icon.png")); // NOI18N
        panelDev4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 68, -1, -1));

        device4.setBackground(new java.awt.Color(255, 0, 204));
        device4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        device4.setText("jToggleButton1");
        panelDev4.add(device4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 22, 326, 30));

        descDev4.setText("jLabel1");
        panelDev4.add(descDev4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 68, 198, -1));

        panelDev2.setBackground(new java.awt.Color(51, 255, 0));
        panelDev2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDev2.setMaximumSize(new java.awt.Dimension(340, 178));
        panelDev2.setMinimumSize(new java.awt.Dimension(340, 178));
        panelDev2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\Industry-Rfid-Signal-icon.png")); // NOI18N
        panelDev2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 76, -1, -1));

        device2.setBackground(new java.awt.Color(51, 255, 0));
        device2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        device2.setText("jToggleButton1");
        panelDev2.add(device2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 26, 326, 30));

        descDev2.setText("jLabel1");
        panelDev2.add(descDev2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 76, 200, -1));

        panelDev3.setBackground(new java.awt.Color(153, 0, 153));
        panelDev3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDev3.setMaximumSize(new java.awt.Dimension(330, 182));
        panelDev3.setMinimumSize(new java.awt.Dimension(330, 182));
        panelDev3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\Industry-Rfid-Signal-icon.png")); // NOI18N
        panelDev3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 80, -1, -1));

        device3.setBackground(new java.awt.Color(153, 0, 153));
        device3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        device3.setText("jToggleButton1");
        panelDev3.add(device3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 28, 320, 30));

        descDev3.setText("jLabel1");
        panelDev3.add(descDev3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 198, -1));

        panelDev6.setBackground(new java.awt.Color(0, 255, 204));
        panelDev6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDev6.setMaximumSize(new java.awt.Dimension(330, 178));
        panelDev6.setMinimumSize(new java.awt.Dimension(330, 178));
        panelDev6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(0, 255, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\Industry-Rfid-Signal-icon.png")); // NOI18N
        panelDev6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 70, -1, -1));

        device6.setBackground(new java.awt.Color(0, 255, 204));
        device6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        device6.setText("jToggleButton1");
        panelDev6.add(device6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 26, 316, 30));

        descDev6.setText("jLabel1");
        panelDev6.add(descDev6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 181, -1));

        panelDev5.setBackground(new java.awt.Color(255, 102, 0));
        panelDev5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelDev5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\deadlocks\\DeadLocks\\src\\main\\java\\com\\sliit\\images\\Industry-Rfid-Signal-icon.png")); // NOI18N
        panelDev5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 72, -1, -1));

        device5.setBackground(new java.awt.Color(255, 102, 0));
        device5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        device5.setText("jToggleButton1");
        panelDev5.add(device5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 24, 316, 30));

        descDev5.setText("jLabel1");
        panelDev5.add(descDev5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 72, 198, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelDev1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelDev2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(panelDev4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelDev5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelDev3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelDev6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDev3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panelDev1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(panelDev2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panelDev5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(panelDev4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panelDev6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel descDev1;
    private javax.swing.JLabel descDev2;
    private javax.swing.JLabel descDev3;
    private javax.swing.JLabel descDev4;
    private javax.swing.JLabel descDev5;
    private javax.swing.JLabel descDev6;
    private javax.swing.JToggleButton device1;
    private javax.swing.JToggleButton device2;
    private javax.swing.JToggleButton device3;
    private javax.swing.JToggleButton device4;
    private javax.swing.JToggleButton device5;
    private javax.swing.JToggleButton device6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelDev1;
    private javax.swing.JPanel panelDev2;
    private javax.swing.JPanel panelDev3;
    private javax.swing.JPanel panelDev4;
    private javax.swing.JPanel panelDev5;
    private javax.swing.JPanel panelDev6;
    // End of variables declaration//GEN-END:variables
}
