/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sliit.views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import org.jnetpcap.Pcap;
import org.jnetpcap.PcapIf;

/**
 *
 * @author Heshani
 */
public class NICListPanel extends javax.swing.JPanel {

    private List<PcapIf> networkInterfacesList;

    /**
     * Creates new form NIC
     */
    public NICListPanel() {
        initComponents();
        getNetworkInterfaces();
    }

    private void getNetworkInterfaces() {

        //get all NICs
        List<PcapIf> devices = new ArrayList<PcapIf>();
        //for any error msg
        StringBuilder errbuf = new StringBuilder();
        int r = Pcap.findAllDevs(devices, errbuf);
        if (r == Pcap.NOT_OK || devices.isEmpty()) {
            System.out.println("Can't read list of devices, error is " + errbuf.toString());
            return;
        }

        this.networkInterfacesList = devices;

        for (PcapIf device : devices) {

            DevicePanel devicePanel = new DevicePanel();

            devicePanel.deviceNameBtn.setText(device.getName());
            devicePanel.descLabel.setText(device.getDescription());

            devPanelContainer.add(devicePanel, "networkInterfacesPanel", 0);
            devPanelContainer.revalidate();

            //add action listener
            DeviceListener deviceListener = new DeviceListener();
            devicePanel.deviceNameBtn.addActionListener(deviceListener);

        }

    }

    class DeviceListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            MainHome.tabbedPane.setSelectedIndex(1);
            MainHome.trafficAnalyzerPanel.removeAll();
            MainHome.trafficAnalyzerPanel.add(new TrafficAnalyserPanel(networkInterfacesList, e.getActionCommand()), "trafficAnalyserPanel", 0);
            MainHome.trafficAnalyzerPanel.revalidate();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devPanelContainer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        devPanelContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 255));
        jLabel6.setText("NETWORK INTERFACES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(devPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 1032, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(devPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel devPanelContainer;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
